{
 "title": "GCP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "最高CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU 使用率百分位數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "5百分位CPU使用率",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "50百分位CPU使用率",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "95百分位CPU使用率",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "99百分位CPU使用率",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "title": "記憶體", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "最高記憶體使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.instance_id}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [
       "metric.label.state",
       "=",
       "used"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/memory/percent_used",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "title": "磁碟", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "最高磁碟使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.instance_id}} {{metric.label.device}}",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.state",
       "=",
       "used",
       "AND",
       "resource.label.zone",
       "=",
       "asia-east1-b"
      ],
      "groupBys": [
       "metric.label.device",
       "resource.label.instance_id"
      ],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/disk/percent_used",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "wide-retina-342307",
      "query": "fetch gce_instance\n| metric 'agent.googleapis.com/disk/percent_used'\n| filter (metric.state == 'used')\n| group_by 1m, [value_percent_used_mean: mean(value.percent_used)]\n| every 1m",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "最高寫入處理量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "resource.label.zone",
       "=",
       "asia-east1-b",
       "AND",
       "metric.label.device_type",
       "=",
       "permanent",
       "AND",
       "metric.label.storage_type",
       "=",
       "pd-balanced"
      ],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "最高讀取處理量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "resource.label.zone",
       "=",
       "asia-east1-b",
       "AND",
       "metric.label.device_type",
       "=",
       "permanent",
       "AND",
       "metric.label.storage_type",
       "=",
       "pd-balanced"
      ],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "網路狀態", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "防火牆檔下流量最高",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/firewall/dropped_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "最高傳送流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "resource.label.zone",
       "=",
       "asia-east1-b",
       "AND",
       "metric.label.loadbalanced",
       "=",
       "false"
      ],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": " 最高接收流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "wide-retina-342307",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}